### ISSUE TITLE
Docker: caddy-ratelimit is not referring to the original IPv6 address.

### ISSUE THREAD

**Issue by sowinski** [mholt/caddy-ratelimit#54]
Hi,

I use Caddy in my IPv4 Caddy network.

The problem is that the Docker NAT is transforming the IPv6 addresses to an IPv4 address, and caddy-ratelimit is referring to this IPv4 address, which is similar for all IPv6 calls. Therefore, the rate limit is not working correctly.

Is it possible to extract the original IPv6 header somehow? Perhaps using the X-Forwarded-For header or something similar?

**Comment by sowinski** [comment]
I use caddy-docker-proxy. What config do you mean exactly? 
(ipv6 support is not enabled in the docker network which I use)

**Comment by mholt** [comment]
Hmm, I don't really know much about caddy-docker-proxy and how it works.

Basically your zone key should be whatever you want to use as a unique key for the rate limit; such as an IP address. If whatever key is being used isn't right, I would change it. That's about as specific as I can get without further details. Maybe ask CDP community instead...

**Comment by mohammed90** [comment]
This is ultimately a Docker question and not something actionable by this module nor Caddy itself. It has to do with your Docker configuration and how you use it. I found this Serverfault question on a similar issue:
https://serverfault.com/questions/1148155/ipv6-docker-userland-proxy-and-identifying-client-source

I recommend you look into how you could fix this in Docker. I found the above link by searching `docker userland proxy ipv6`.

**Comment by polarathene** [comment]
Just for anyone landing here, Docker should have this resolved from v27 onwards I think?

In the past containers would not be implicitly assigned to a private IPv6 subnet like they are for IPv4 on the default bridge network type. This required enabling IPv6 experimental support for the docker daemon prior to v27, otherwise due to `userland-proxy` (default enabled), incoming IPv6 connections on the host were routed to the IPv4 only connection on the containers subnet gateway IP.

Another alternative is to not route traffic like that when source IP is important and disable the userland proxy. That would refuse the IPv6 connection instead and the client should then use IPv4 to connect successfully.
