### ISSUE TITLE
global rate_limit

### ISSUE THREAD

**Issue by vahidalvandi** [mholt/caddy-ratelimit#71]
hi i want to use this in global . do it work ?

```
{
	rate_limit {
				zone dynamic_zone {
						key {http.request.remote_ip}
						events 2
						window 5s
				}
		}
}
```

**Comment by mohammed90** [comment]
You can user [named routes](https://caddyserver.com/docs/caddyfile/concepts#named-routes) or [snippets](https://caddyserver.com/docs/caddyfile/concepts#snippets).

**Comment by vahidalvandi** [comment]
please show me with exa

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in this Caddy plugin. It looks more like a question about how to use it rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
